#!/bin/sh
#
# blackboxtests -- run black box tests for wibbr
#
# This script runs some automatic black box tests for wibbr. The tests
# are structured as follows: first the initial tree to be backed up is
# created, and backed up. Then the tree is updated for the next
# generation, which gets backed up. This is repeated for each
# generation. In addition, a manifest file is created for each
# generation.
#
# After all generations have been created and backed up, they are
# restored one by one. A manifest file is created for the restored tree,
# and compared to the one that was created when the original generation
# was backed up. If there are any problems, the testing aborts.
#
# The generations are created either by tarballs or shell scripts. The
# former are unpacked into a temporary directory (each generation is
# unpacked on top of the previous one), and the scripts are run to
# modify the temporary directory for the next generation.
#
# Each test case is put into its own directory, and the directory should
# contain files named "gen??.tar.gz" (for the tarballs) or "gen??.sh"
# (for the shell scripts), where "??" is a two-digit number identifying
# the generation.
#
# This script outputs nothing if everything went well, and errors if
# something went badly.

set -e

# tmp="tmp"; rm -rf "$tmp"; mkdir "$tmp"
tmp=$(mktemp -d)

CONFIG="--cache-dir=$tmp/cache --local-store=$tmp/store"

MANIFESTOPTS="-i Inode -i Ctime -i Atime"

for dir in "$@"
do
    echo "Testing $dir..."
    rm -rf "$tmp"/*
    mkdir "$tmp/root"
    
    find "$dir" -maxdepth 1 -name 'gen[0-9][0-9].*' -type f |
    sort |
    nl |
    while read i gen
    do
        pre=$(echo  "$gen" | sed 's,/gen\([0-9][0-9]\)[^/]*$,/pre\1,').sh
        post=$(echo "$gen" | sed 's,/gen\([0-9][0-9]\)[^/]*$,/post\1,').sh

        case "$gen" in
        *.tar.gz)
            tar -C "$tmp/root" -xzf "$gen"
            ;;
        *.sh)
            sh "$gen" "$tmp/root"
            ;;
        esac
        
        python manifest.py $MANIFESTOPTS "$tmp/root" > "$tmp/manifest-$i"
        
        if [ -e "$pre" ] && ! sh "$pre" "$tmp"
        then
            echo "Pre-check $pre failed, aborting" 1>&2
            exit 1
        fi

        python wibbr.py $CONFIG -C "$tmp/root" backup .

        if [ -e "$post" ] && ! sh "$post" "$tmp"
        then
            echo "Post-check $post failed, aborting" 1>&2
            exit 1
        fi
    done
    
    python wibbr.py $CONFIG generations |
    nl |
    while read i genid
    do
        rm -rf "$tmp/root"
        mkdir "$tmp/root"
        python wibbr.py $CONFIG -C "$tmp/root" restore "$genid"
        python manifest.py $MANIFESTOPTS "$tmp/root" > "$tmp/manifest2-$i"
        diff -u -U 15 "$tmp/manifest-$i" "$tmp/manifest2-$i"
    done
done

rm -rf "$tmp"
