#!/bin/sh
#
# license-check -- verify that each file contains copyright statement/license
#
# This script checks that each of the files given on the command line contain
# copyright statement and a reference to the GPL license. It prints out
# an error message to stderr for each file that fails the check, and exits
# with zero if there were no failures, or one if there were.

whine()
{
    echo "Error: $@" 1>&2
}

has_copyright()
{
    grep -E "Copyright (\(C\) )?[0-9][0-9][0-9][0-9].*[^0-9]" "$1" > /dev/null
}

has_gpl()
{
    # The following construct is so that the source code of this file
    # does not match the pattern itself.

    phrase1="This program is"
    phrase1="$phrase1 free software"

    phrase2="GNU General Public"
    phrase2="$phrase2 License"

    grep "$phrase1" "$1" > /dev/null &&
    grep "$phrase2" "$1" > /dev/null
}

exit=0
for file in "$@"
do
    if ! has_copyright "$file"
    then
        whine "$file has no copyright statement"
        exit=1
    fi
    if ! has_gpl "$file"
    then
        whine "$file does not refer to the GPL"
        exit=1
    fi
done

exit $exit
