#!/bin/sh
#
# license-check -- verify that each file contains copyright statement/license
#
# This script checks that each of the files given on the command line contain
# copyright statement and a reference to the GPL license. It prints out
# an error message to stderr for each file that fails the check, and exits
# with zero if there were no failures, or one if there were.
#
# Copyright (C) 2007  Lars Wirzenius <liw@iki.fi>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

whine()
{
    echo "Error: $@" 1>&2
}

has_copyright()
{
    grep -E "Copyright (\(C\) )?[0-9][0-9][0-9][0-9].*[^0-9]" "$1" > /dev/null
}

has_gpl()
{
    # The following construct is so that the source code of this file
    # does not match the pattern itself.

    phrase1="This program is"
    phrase1="$phrase1 free software"

    phrase2="GNU General Public"
    phrase2="$phrase2 License"

    grep "$phrase1" "$1" > /dev/null &&
    grep "$phrase2" "$1" > /dev/null
}

exit=0
for file in "$@"
do
    if ! has_copyright "$file"
    then
        whine "$file has no copyright statement"
        exit=1
    fi
    if ! has_gpl "$file"
    then
        whine "$file does not refer to the GPL"
        exit=1
    fi
done

exit $exit
