#!/bin/sh
#
# Check that the manual page contains all options.
#
# Copyright (C) 2006, 2007  Lars Wirzenius <liw@iki.fi>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

from_manpage()
{
    (man -l obnam.1 2>/dev/null) | 
    grep '^       -' | 
    tr , '\n' | 
    sed 's/^ *//;s/[= ].*//' |
    sort
}

from_code()
{
    python -c 'import obnamlib; obnamlib.config.print_option_names()' |
    sort
}

temp1=$(mktemp)
from_manpage > $temp1

temp2=$(mktemp)
from_code > $temp2

diff -u $temp1 $temp2
