#!/usr/bin/python
# Copyright (C) 2008  Lars Wirzenius <liw@liw.fi>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import sys
import obnamlib


def dump_component(cmp, indent):
    spaces = " " * (indent * 2)
    print "%skind: %s" % (spaces, obnamlib.cmp_kinds.nameof(cmp.kind))
    if obnamlib.cmp_kinds.is_composite(cmp.kind):
        for child in cmp.children:
            dump_component(child, indent+1)
    else:
        print "%sstring: %s" % (spaces, cmp.string)

def dump(obj):
    print "kind:", obnamlib.obj_kinds.nameof(obj.kind)
    print "id:", obj.id
    obj.prepare_for_encoding()
    for c in obj.components:
        print "component:"
        dump_component(c, 1)
    print


factory = obnamlib.ObjectFactory()
for filename in sys.argv[1:]:
    data = file(filename).read()
    obj = factory.decode_object(data)
    dump(obj)
