#!/usr/bin/python
# Copyright (C) 2009  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import os
import sys
import time

import obnamlib


def find_objids(fs):
    basenames = fs.listdir('.')
    return [x[:-len('.obj')] for x in basenames if x.endswith('.obj')]


fs = obnamlib.LocalFS(sys.argv[1])
repo = obnamlib.Repository(fs, obnamlib.DEFAULT_NODE_SIZE, 
                       obnamlib.DEFAULT_UPLOAD_QUEUE_SIZE, None,
                       obnamlib.IDPATH_DEPTH,
                       obnamlib.IDPATH_BITS,
                       obnamlib.IDPATH_SKIP,
                       time.time, 0)
for objid in find_objids(fs):
    obj = repo.get_object(objid)
    print 'id %s (%s):' % (obj.id, obj.__class__.__name__)
    for name in obj.fieldnames():
        print '  %-10s %s' % (name, repr(getattr(obj, name)))
