#!/usr/bin/python
# Copyright 2010  Lars Wirzenius
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import os
import sys
import time

import obnamlib


def main():
    n = int(sys.argv[1])
    dirname = sys.argv[2]
    depth = int(sys.argv[3])
    bits = int(sys.argv[4])
    skip = int(sys.argv[5])
    
    idpath = obnamlib.IdPath(dirname, depth, bits, skip)
    start = time.time()
    for i in xrange(n):
        path = idpath.convert(i)
        dirname = os.path.dirname(path)
        if not os.path.exists(dirname):
            os.makedirs(dirname)
        with open(path, 'w'):
            pass
    end = time.time()

    duration = end - start
    speed = n / duration
    print '%d ids, %.1f seconds, %.1f ids/s' % (n, duration, speed)    

if __name__ == '__main__':
    main()
