#!/usr/bin/python
# Copyright 2012  Lars Wirzenius
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import os
import sys

import obnamlib


dirname = sys.argv[1]
count_to = int(sys.argv[2])
filename = os.path.join(dirname, 'counter')

fs = obnamlib.LocalFS('/')
lm = obnamlib.LockManager(fs, 60)

for i in range(count_to):
    lm.lock([dirname])
    if fs.exists(filename):
        data = fs.cat(filename)
        counter = int(data)
        counter += 1
        fs.overwrite_file(filename, str(counter))
    else:
        fs.write_file(filename, str(1))
    lm.unlock([dirname])

