#!/usr/bin/env python
# Copyright 2014  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# =*= License: GPL-3+ =*=


from meliae import loader
from pprint import pprint as pp
import sys


om = loader.load(sys.argv[1])
om.remove_expensive_references()
print om.summarize()
print

for type_name in sys.argv[2:]:
    objs = om.get_all(type_name)
    for obj in objs[:5]:
        pp(obj.p)
        print om.summarize(obj)
        print
