#!/usr/bin/env python
# Copyright 2010-2015  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import sys
import time

import obnamlib


def measure(n, func):
    start = time.clock()
    for i in range(n):
        func()
    end = time.clock()
    return end - start


def main():
    n = int(sys.argv[1])
    fs = obnamlib.LocalFS('.')
    fs.connect()
    metadata = obnamlib.read_metadata(fs, '.')
    encoded = obnamlib.fmt_6.metadata_codec.encode_metadata(metadata)
    calibrate = measure(n, lambda: None)
    encode = measure(
        n, lambda: obnamlib.fmt_6.metadata_codec.encode_metadata(metadata))
    decode = measure(
        n, lambda: obnamlib.fmt_6.metadata_codec.decode_metadata(encoded))
    print 'encode: %.1f s' % (n/(encode - calibrate))
    print 'decode: %.1f s' % (n/(decode - calibrate))

if __name__ == '__main__':
    main()
