#!/usr/bin/env python
# Copyright 2014  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# =*= License: GPL-3+ =*=


'''Create files of specified size, filled with junk.'''


import os

import cliapp


class MakeData(cliapp.Application):

    def add_settings(self):
        self.settings.bytesize(
            ['size'],
            'how large a file to generate',
            default=0)

    def process_args(self, filenames):
        for filename in filenames:
            self.create_file(filename, self.settings['size'])

    def create_file(self, filename, size):
        self.create_parent_directory(filename)
        with open(filename, 'w') as f:
            self.write_data(f, size)

    def create_parent_directory(self, filename):
        dirname = os.path.dirname(filename)
        if not os.path.exists(dirname):
            os.makedirs(dirname)

    def write_data(self, f, size):
        chunk = 'x' * 2**20
        written = 0
        while written < size:
            n = min(len(chunk), size - written)
            f.write(chunk[:n])
            written += n


MakeData().run()
