#!/usr/bin/python
# Copyright 2010  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import pstats
import sys

if len(sys.argv) not in [2, 3]:
    sys.stderr.write('Usage: obnam-viewprof foo.prof [sort-order]\n')
    sys.exit(1)

if len(sys.argv) == 3:
    order = sys.argv[2]
else:
    order = 'cumulative'

p = pstats.Stats(sys.argv[1])
p.strip_dirs()
p.sort_stats(order)
p.print_stats()
p.print_callees()
