#!/bin/sh
#
# This is a script Lars Wirzenius uses to publish docs on the Internet.
# It's not useful for anyone else, as it requires access to the right
# host.
#
# It is assumed that the docs have been built already.

# Copyright 2014  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# =*= License: GPL-3+ =*=

host="pieni.net"
path="code.liw.fi/obnam"

rsync manual/*.pdf manual/*.html "$host:$path/manual/."
rsync yarns/yarns.pdf yarns/yarns.html "$host:$path/"
