#!/usr/bin/python
# Copyright (C) 2009  Lars Wirzenius <liw@liw.fi>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


import logging
import sys

import obnamlib

BLOCK_SIZE = 4096

def disk_usage(fs, pathname):
    st = fs.lstat(pathname)
    nblocks = st.st_size / BLOCK_SIZE
    if st.st_size % BLOCK_SIZE:
        nblocks += 1
    return nblocks * BLOCK_SIZE

logging.basicConfig(level=logging.WARNING)
for url in sys.argv[1:]:
    fs = obnamlib.VfsFactory().new(url, None)
    fs.connect()
    du = 0
    for dirname, dirnames, filenames in fs.depth_first('.'):
        for x in [dirname] + filenames:
            du += disk_usage(fs, x)
    fs.close()
    print "%d\t%s" % (du, url)

