#!/usr/bin/python


"""Show the contents of a Wibbr storage block."""


import sys

from wibbrlib import *


recursive_component_types = (
    OBJPART,
)


def format_objmap(data):
    uuids = []
    while data:
        uuids.append(data[:36])
        data = data[36:]
    return "%s->%s" % (uuids[0], ",".join(uuids[1:]))


component_data_formatters = {
    OBJTYPE: lambda data: object_type_name(varint_decode(data, 0)[0]),
    FILESIZE: lambda data: varint_decode(data, 0)[0],
    OBJMAP: format_objmap,
}


def show_component(type, data, indent=0):
    x = " " * (indent * 2)
    print x + "Component:", type, component_type_name(type)
    if type in recursive_component_types:
        pos = 0
        while pos < len(data):
            (type2, data2, pos) = component_decode(data, pos)
            show_component(type2, data2, indent+1)
    else:
        fmt = component_data_formatters.get(type, repr)
        print x + "  data:", fmt(data)


def show_block(filename):
    print "======== block:", filename, "==========="
    f = file(filename, "r")
    str = f.read()
    f.close()
    pos = 0
    while pos < len(str):
        (type, data, pos) = component_decode(str, pos)
        show_component(type, data)
        print


def main():
    for filename in sys.argv[1:]:
        show_block(filename)


if __name__ == "__main__":
    main()
