#!/usr/bin/python


import sys

import obnamlib


def show_component(comp, indent=0):
    kind = obnamlib.cmp_kinds.nameof(comp.kind)
    sys.stdout.write("%*scomponent: %s" % (indent, "", kind))
    if obnamlib.cmp_kinds.is_composite(comp.kind):
        sys.stdout.write("\n")
        for c in comp.children:
            show_component(c, indent + 1)
    elif comp.kind == obnamlib.OBJKIND:
        objkind, x = obnamlib.varint.decode(str(comp), 0)
        sys.stdout.write(" %s\n" % obnamlib.obj_kinds.nameof(objkind))
    else:
        content = repr(str(comp))
        sys.stdout.write(" %s\n" % content)


def show_block(filename):
    print "Block", filename
    
    blob = file(filename).read()
    cookie = obnamlib.BlockFactory.BLOCK_COOKIE
    if not blob.startswith(cookie):
        print "Does not start with cookie!"
    else:
        of = obnamlib.ObjectFactory()
        pos = len(cookie)
        while pos < len(blob):
            comp, pos = of.decode_component(blob, pos)
            show_component(comp)
    
    print


def main():
    for filename in sys.argv[1:]:
        show_block(filename)


if __name__ == "__main__":
    main()
