#!/bin/bash
#
# Obnam test: backup and verify many generations of data.
#
# Copyright 2012  Lars Wirzenius
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -x

die()
{
    echo "$@" 1>&2
    exit 1
}

[ "$#" = 3 ] || die "Bad usage, read source!"

N="$1"
repo="$2"
client="$3"
root="$(mktemp -d)"
amount="1k"

conf="$(mktemp)"
cat <<EOF > "$conf"
[config]
client-name = $client
quiet = yes
log = $client.log
EOF

seq "$N" |
while read gen
do
    genbackupdata --quiet --create="$amount" "$root" --seed="$RANDOM"
    find "$root" -exec touch --date="1970-01-01 00:00:$gen" '{}' ';'
    ./verification-test backup "$repo" "$root" "$conf"
done

while true
do
    ./verification-test verify "$repo" "$root" "$conf"
    ret="$?"
    if [ "$ret" = 0 ]
    then
        break
    elif [ "$ret" != 42 ]
    then
        echo "$client failed verification" 1>&2
        exit 1
    fi
done

rm -rf "$conf" "$root"

