#!/bin/sh
#
# Obnam test: backup and verify many generations of data.
#
# Copyright 2012  Lars Wirzenius
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

die()
{
    echo "$@" 1>&2
    exit 1
}

[ "$#" = 3 ] || die "Bad usage, read source!"

N="$1"
repo="$2"
client="$3"
root="$(mktemp -d)"
amount="1k"

conf="$(mktemp)"
cat <<EOF > "$conf"
[config]
client-name = $client
quiet = yes
EOF

seq "$N" |
while read gen
do
    echo "$gen"
    genbackupdata --quiet --create="$amount" "$root"
    ./verification-test backup "$repo" "$root" "$conf"
done
./verification-test verify "$repo" "$root" "$conf"

rm -rf "$conf" "$root"

