#!/bin/sh

die()
{
    echo "$@" 1>&2
    echo "Exit code: $exit_code" 1>&2
    echo "Stderr contents:" 1>&2
    sed 's/.*/  &/' "$stderr_file" 1>&2
    exit 1
}

run()
{
    "$@" 2>"$stderr_file"
    exit_code=$?
}

require_exit_code()
{
    if [ "$exit_code" != $1 ]
    then
        die "Program did not exit with code $1"
    fi
}

require_stderr_match()
{
    if ! grep "$1" "$stderr_file" > /dev/null
    then
        die "Stderr does not match '$1'"
    fi
}

stderr_file=$(mktemp)

# Check no arguments
run ./odirect_read
require_exit_code 1
require_stderr_match "exactly one argument"

# Check too many arguments
run ./odirect_read foo bar
require_exit_code 1
require_stderr_match "exactly one argument"

# Check non-existing file
run ./odirect_read nonexisting
require_exit_code 1
require_stderr_match "Trying to open"

# Check writing problems
run ./odirect_read README > /dev/full
require_exit_code 1
require_stderr_match "Writing to stdout"

# Check existing normal file, this should succeed
run ./odirect_read README > /dev/null
require_exit_code 0

# Cleanup
rm -f "$stderr_file"
