#!/bin/sh
# Copyright 2012  Lars Wirzenius
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Do not include roots from previous generations in a new generation,
# when the user stops specifying them.

set -eu

cd "$DATADIR"
tar -xf "$SRCDIR/test-data/repo-format-5-encrypted-gzipped.tar.gz"
"$SRCDIR/tests/obnam" convert5to6 -r repo
"$SRCDIR/tests/obnam" restore -r repo --to restored
summain -r "restored/$DATADIR/data" > restored.summain
diff -u data.summain restored.summain

