#!/bin/sh
# Copyright 2011  Lars Wirzenius
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu

gpgkey='3B1802F81B321347'
fingerprint='4E2AF28A3D824CF2B3F1FE733B1802F81B321347'
gpgkey2='DF3D13AA11E69900'

# Make a backup with the default key ($gpgkey).
$SRCDIR/tests/backup --encrypt-with="$gpgkey"

# Add new key. "rainyday" is the name of the client.
$SRCDIR/tests/obnam --encrypt-with="$gpgkey" add-key --keyid="$gpgkey2" \
    rainyday

# Remove the old key.
$SRCDIR/tests/obnam --encrypt-with="$gpgkey2" remove-key --keyid="$gpgkey" \
    rainyday

# Remove the old key from the gpg keyring.
export GNUPGHOME="$DATADIR/gpg"
gpg --batch --delete-secret-key "$fingerprint"

# Verify that the backup is still readable, now with the new key.
$SRCDIR/tests/restore --encrypt-with="$gpgkey2"
$SRCDIR/tests/verify

