#!/bin/sh
# Copyright 2011  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

cachedir="$DATADIR/data/cache"
mkdir "$cachedir"
echo -n 'Signature: 8a477f597d28d172789f06886806bc55' \
    > "$cachedir/CACHEDIR.TAG"
echo foo > "$cachedir/foo"

$SRCDIR/tests/backup --exclude-caches
$SRCDIR/tests/restore

find "$DATADIR/restored" -name cachdir
