#!/bin/sh
# Copyright 2011  Lars Wirzenius
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

dd if=/dev/zero of="$DATADIR/data/aaa" bs=1M count=1 2> /dev/null

$SRCDIR/tests/backup --deduplicate=never
$SRCDIR/tests/backup --deduplicate=never

$SRCDIR/tests/obnam genids > "$DATADIR/genids-1"
$SRCDIR/tests/obnam forget $(cat "$DATADIR/genids-1")

# Remove encryption metadata, if any.
rm -f "$DATADIR/repo/chunks/key"
rm -f "$DATADIR/repo/chunks/userkeys"

find "$DATADIR/repo/chunks" -type f -ls

