#!/bin/sh
# Copyright 2011  Lars Wirzenius
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This tests for a bug in Obnam as of 0.24.
# http://liw.fi/obnam/bugs/generation-time-stamps-wrong/

set -e

# Obnam settings.
opts="--quiet --no-default-config"

# Backup.
./obnam $opts backup -r "$DATADIR/repo" "$DATADIR/data" \
    --pretend-time='2007-08-12 01:02:03'

# Print out the generation timestamp.
./obnam $opts ls -r "$DATADIR/repo" | head -n1
