#!/bin/sh
# Copyright 2011  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

# Named pipes do not work with sftp/paramiko. Skip this test?
if [ "$OBNAM_TEST_SFTP_ROOT" = yes ]
then
    exit 0
fi

# Create a named socket.
python -c '
import platform
if platform.system() == "FreeBSD":
    # Cannot mknod sockets on FreeBSD.
    raise SystemExit(0)
import os, stat
filename = os.path.join(os.environ["DATADIR"], "data", "socket")
os.mknod(filename, 0600 | stat.S_IFSOCK)
'

$SRCDIR/tests/backup
$SRCDIR/tests/restore
$SRCDIR/tests/verify

