#!/bin/sh
# Copyright 2011  Lars Wirzenius
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Do not include roots from previous generations in a new generation,
# when the user stops specifying them.

set -e

mkdir "$DATADIR/data/root1"
echo foo > "$DATADIR/data/root1/foo"

mkdir "$DATADIR/data/root2"
echo bar > "$DATADIR/data/root2/bar"

# Run the first backup with root1.
./obnam --quiet --no-default-config backup -r "$DATADIR/repo" \
    "$DATADIR/data/root1"

# Run the second backup with root2.
./obnam --quiet --no-default-config backup -r "$DATADIR/repo" \
    "$DATADIR/data/root2"

# Verify the latest generation has nothing from root1.
./obnam --quiet --no-default-config -r "$DATADIR/repo" ls | grep root1 || true
