#!/bin/sh
# Copyright 2011  Lars Wirzenius
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Helper script for cmdtest tests: run a backup.

export GNUPGHOME="$DATADIR/gpg"

out="$(mktemp)"
err="$(mktemp)"

$SRCDIR/obnam \
    --client-name=rainyday \
    --quiet \
    --no-default-config \
    -r "$(cat $DATADIR/repourl)" \
    --weak-random \
    --log="$DATADIR/obnam.log" \
    --trace=vfs \
    --trace=repo \
    "$@" > "$out" 2> "$err"
exit=$?

sed "s#$DATADIR#TMP#g" "$out"
sed "s#$DATADIR#TMP#g" "$err" 1>&2

rm -f "$out" "$err"
exit "$exit"
