#!/bin/sh
# Copyright 2011  Lars Wirzenius
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

# It's possible to have timestamps before the epoch, i.e., negative
# ones. For example, in the UK during DST, "touch -t 197001010000"
# will create one.

echo foo > "$DATADIR/data/foo"
python -c '
import os
os.utime(os.path.join(os.environ["DATADIR"], "data", "foo"), (-3600, -3600))
'

$SRCDIR/tests/backup
$SRCDIR/tests/restore
$SRCDIR/tests/verify

