#!/bin/sh
# Copyright 2012  Lars Wirzenius
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

# It seems paramiko can't create dangling symlinks. Skip this if
# restoring over sftp.
if [ "$OBNAM_TEST_SFTP_ROOT" != yes ]
then
    # Make the backup root be a symlink.
    mv "$DATADIR/data" "$DATADIR/data.real"
    ln -s data.real "$DATADIR/data"

    $SRCDIR/tests/backup
    $SRCDIR/tests/restore
    $SRCDIR/tests/verify '
        {
            gsub(/^Name: \/.*\//, "Name: ")
            print
        }
    '
fi

