#!/bin/sh
# Copyright 2011  Lars Wirzenius
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -e

# Make a copy of the gpg homedir. This is so that we don't get gpg
# accidentally changing anything, such as the random seed file.
cp -a "$SRCDIR/test-gpghome" "$DATADIR/gpg"
chmod go= "$DATADIR/gpg"

# Generate some test data.
genbackupdata --quiet --create=100k "$DATADIR/data"


if [ "$OBNAM_TEST_SFTP_REPOSITORY" = yes ]
then
    REPO="sftp://localhost$DATADIR/repo"
else
    REPO="$DATADIR/repo"
fi
echo "$REPO" > "$DATADIR/repourl"

if [ "$OBNAM_TEST_SFTP_ROOT" = yes ]
then
    ROOT="sftp://localhost$DATADIR/data"
    RESTORED="sftp://localhost$DATADIR/restored"
else
    ROOT="$DATADIR/data"
    RESTORED="$DATADIR/restored"
fi
echo "$ROOT" > "$DATADIR/rooturl"
echo "$RESTORED" > "$DATADIR/restoredurl"

