#!/bin/sh
# Copyright 2011  Lars Wirzenius
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Make two backup generations with different contents. Make sure the
# last generation can be restored correctly.

set -e

find "$DATADIR/data" -mindepth 1 -delete
echo foo > "$DATADIR/data/foo"

$SRCDIR/tests/backup

rm "$DATADIR/data/foo"
echo bar > "$DATADIR/data/bar"

$SRCDIR/tests/backup
$SRCDIR/tests/restore
$SRCDIR/tests/verify

