#!/bin/sh
# Copyright 2012  Lars Wirzenius
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Make two backup generations with different contents. Make sure the
# last generation can be restored correctly.

set -e

# This only works with local filesystem access, not over sftp.
# It also requires user_xattr to be set on the filesystem.
# If both requirements are not met, skip the test.
echo foo > "$DATADIR/data/foo"
if [ "$OBNAM_TEST_SFTP_ROOT" != yes ] &&
   setfattr --name=user.foo --value=bar "$DATADIR/data/foo" 2>/dev/null
then
    $SRCDIR/tests/backup

    setfattr --name=user.foo --value=bar "$DATADIR/data/foo"

    $SRCDIR/tests/backup
    $SRCDIR/tests/restore
    $SRCDIR/tests/verify
fi
