#!/bin/sh

set -eu

OUTPUT="$1"
TITLE="$2"
AUTHOR="$3"
VERSION="$4"
TRANS_DE="$5"
shift 5

cat > 000.mdwn <<EOF
% $TITLE
% $AUTHOR
  $TRANS_DE
% $VERSION
EOF

pandoc --smart --toc --chapters --number-sections -V lang=german -V geometry:a4paper -o "$OUTPUT" 000.mdwn "$@"
rm -f 000.mdwn
