#!/usr/bin/python

import optparse
import pstats
import sys

parser = optparse.OptionParser()
parser.add_option('--order', default='cumulative')
parser.add_option('--callees', action='store_true')

options, args = parser.parse_args()

p = pstats.Stats(args[0])
p.strip_dirs()
p.sort_stats(options.order)
if options.callees:
    p.print_callees()
else:
    p.print_stats()

