#!/usr/bin/python

import logging
import sys

import obnamlib

BLOCK_SIZE = 4096

def disk_usage(fs, pathname):
    st = fs.lstat(pathname)
    nblocks = st.st_size / BLOCK_SIZE
    if st.st_size % BLOCK_SIZE:
        nblocks += 1
    return nblocks * BLOCK_SIZE

logging.basicConfig(level=logging.DEBUG)
for url in sys.argv[1:]:
    fs = obnamlib.SftpFS(url)
    du = 0
    for dirname, dirnames, filenames in fs.depth_first('.'):
        for x in [dirname] + filenames:
            du += disk_usage(fs, x)
    fs.close()
    print "%d\t%s" % (du, url)

