#!/bin/sh
# Copyright (C) 2009  Lars Wirzenius <liw@liw.fi>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -e

opts="--encrypt-to 490C9ED1 --sign-with 490C9ED1 --gpg-home sample-gpg-home"
opts="$opts --store test.store --host hostid"

rm -rf test.*
mkdir test.tree
(
cd test.tree
echo foo > foo
mkdir emptydir
mkdir dir
echo bar > dir/bar
)

./obnam backup $opts test.tree

./obnam fsck $opts

./obnam objtree $opts > test.dot
dot -Tpng test.dot > test.png

./obnam generations $opts |
tail -n 1 |
xargs ./obnam show $opts > test.show

./obnam showobjs $opts > test.objs
